version: "3.8"

services:
  kafka:
    container_name: kafka
    image: bitnamilegacy/kafka:latest
    restart: no
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:19092
      # - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "19092:9094"
    networks:
      - my-network
    volumes:
      - kafka-data:/bitnami/kafka # window  

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    restart: no
    depends_on:
      - kafka
    ports:
      - "8001:8080"
    environment:
      # Local Kafka cluster
      - KAFKA_CLUSTERS_0_NAME=local-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_READONLY=false
      - KAFKA_CLUSTERS_0_TOPIC_AUTO_CREATE=true

      # Cloud Kafka cluster (uncomment and set credentials to enable)
      - KAFKA_CLUSTERS_1_NAME=${KAFKA_CLOUD_NAME}
      - KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS=${KAFKA_CLOUD_SERVER}
      - KAFKA_CLUSTERS_1_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_CLUSTERS_1_PROPERTIES_SASL_MECHANISM=PLAIN
      - KAFKA_CLUSTERS_1_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule
        required username="${KAFKA_CLOUD_USERNAME}"
        password="${KAFKA_CLOUD_PASSWORD}";
      - KAFKA_CLUSTERS_1_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=https
      - KAFKA_CLUSTERS_1_PROPERTIES_CLIENT_ID=kafka-ui-client
      - KAFKA_CLUSTERS_1_PROPERTIES_GROUP_ID=kafka-ui-group
    networks:
      - my-network
    user: root

networks:
  my-network:
    driver: bridge

volumes:
  kafka-data:
